import { FaReact } from "react-icons/fa";

import { SiTailwindcss } from "react-icons/si";
import { SiAxios } from "react-icons/si";
<SiAxios />;
import { SiNextui } from "react-icons/si";
export const PortfoliosData = [
  {
    id: 1,
    enTitle: "DigiTize",
    frTitle: "دیجی تایز",
    tools: [
      { title: "React Js", icon: <FaReact /> },
      { title: "Tailwind Css", icon: <SiTailwindcss /> },
      { title: "Swiper" },
      { title: "Formik React", icon: <FaReact /> },
      { title: "NextUi", icon: <SiNextui /> },
      { title: "Axios", icon: <SiAxios /> },
      { title: "React Context" },
      { title: "React Reducer" },
    ],
    mainImages: {
      pImg: "https://s27.uupload.ir/files/osaris/portfolio-digitize/digi-ph-home.png",
      dImg: "https://s27.uupload.ir/files/osaris/portfolio-digitize/digi-desk-home.png",
    },
    order: 1,
    description: [
      {
        enTitle: "Home Page and Categories",
        frTitle: "صفحه اصلی و دسته بندی ها",
        icon: "",
        pImg: "https://s27.uupload.ir/files/osaris/portfolio-digitize/digi-ph-home.png",
        dImg: "https://s27.uupload.ir/files/osaris/portfolio-digitize/digi-desk-home.png",
        enParas: [
          "In this section , the home page of the website , various categories and slider of products whit discount are designed ",
          "In each category , users can view related products",
        ],
        frParas: [
          "در این بخش ، صفحه اصلی ، دسته بندی های مختلف سایت و اسلایدری از محصولات تخفیف دار قرار دارد.",
          "کاربران میتوانند در هر دسته بندی محصولات مرتبط را مشاهده کنند.",
        ],
      },
      {
        enTitle: "Individual Product Page",
        frTitle: "صفحه جزعیات محصول",
        icon: "",
        pImg: "https://s27.uupload.ir/files/osaris/portfolio-digitize/digi-ph-phones.png",
        dImg: "https://s27.uupload.ir/files/osaris/portfolio-digitize/digi-desk-singleSection-laptops.png",
        enParas: [
          "There is the individual page for each product ",
          "Users can view all the details of the selected product on this page",
          "They can chose the color and add the product in shopping cart",
        ],
        frParas: [
          "برای هر محصول صفحه فردی طراحی شده است",
          "کاربر میتواند جزعیات کامل محصولات را مشاهده کند ",
          "رنگ مورد نظر خود را انتخاب کرده و به سبد خرید اضافه کند",
        ],
      },
      {
        enTitle: "Shopping Cart",
        frTitle: "سبد خرید",
        icon: "",
        pImg: "https://s27.uupload.ir/files/osaris/portfolio-digitize/digi-ph-cart.png",
        dImg: "https://s27.uupload.ir/files/osaris/portfolio-digitize/digi-desk-cart.png",
        enParas: [
          "Users can add products to their shopping cart",
          "They can see the details of added products",
          "They can increase or decrease the number of selected products",
          "ّFinally , They can see the total price and complete their purchase",
        ],
        frParas: [
          "کابر ها میتوانند محصولات را به سبد خرید اضافه کنند",
          "میتوانند جزعیات محصولات اضافه شده را مشاهده کنند",
          "همچنین میتوانند تعداد هر محصول را افزایش یا کاهش دهند",
          " و در نهایت میتوانند جمع قیمت نهایی را مشاهده و خرید خود را تکمیل کنند",
        ],
      },
      {
        enTitle: "Wishlist",
        frTitle: "علاقمندی ها",
        icon: "",
        pImg: "https://s27.uupload.ir/files/osaris/portfolio-digitize/digi-ph-interests.png",
        dImg: "https://s27.uupload.ir/files/osaris/portfolio-digitize/digi-desk-interests.png",
        enParas: [
          "Users can add their favorite products to their wishlist",
          "They can see the details of the added products and add them to the cart. ",
        ],
        frParas: [
          "کاربران میتوانند محصولات مورد علاقه خود را به لیست علاقمندی اضافه کنند",
          "تمام جزعیات محصول قابل مشاهده میباشد و میتوانند ان را به سبد خرید خود اضافه کنند.",
        ],
      },
      {
        enTitle: "Product Filters",
        frTitle: "فیلتر محصولات",
        icon: "",
        pImg: "https://s27.uupload.ir/files/osaris/portfolio-digitize/digi-ph-filters.png",
        dImg: "https://s27.uupload.ir/files/osaris/portfolio-digitize/digi-desk-phones.png",
        enParas: [
          "Users can filter products in each category based on their specification",
          "The filter options for different categories are depending on the product attributes within them!",
        ],
        frParas: [
          "کاربران میتوانند محصولات در هر دسته بندی را بر اساس ویژگی های آنها فیلتر کنند.",
          "!گزینه های فیلتر برای دسته بندی های مختلف بستگی به ویژگی های محصولات داخل آنها دارد",
        ],
      },
      {
        enTitle: "Product Search",
        frTitle: "جستجوی محصول",
        icon: "",
        pImg: "https://s27.uupload.ir/files/osaris/portfolio-digitize/digi-ph-phones.png",
        dImg: "https://s27.uupload.ir/files/osaris/portfolio-digitize/digi-desk-waches.png",
        enParas: [
          "Users can search among all the products on the site based on the product name",
        ],
        frParas: [
          "کاربران میتوانند بر اساس نام محصول بین تمامی محصولات جستجو کنند.",
        ],
      },
    ],
  },
  {
    id: 1,
    enTitle: "DigiTize",
    frTitle: "دیجی تایز",
    tools: [
      { title: "React Js", icon: <FaReact /> },
      { title: "Tailwind Css", icon: <SiTailwindcss /> },
      { title: "Swiper" },
      { title: "Formik React", icon: <FaReact /> },
      { title: "NextUi", icon: <SiNextui /> },
      { title: "Axios", icon: <SiAxios /> },
      { title: "React Context" },
      { title: "React Reducer" },
    ],
    mainImages: {
      pImg: "./digitize/phone/digi-ph-home.png",
      dImg: "./digitize/digi-desk-home.png",
    },
    order: 1,
    description: [
      {
        enTitle: "Home Page and Categories",
        frTitle: "صفحه اصلی و دسته بندی ها",
        icon: "",
        pImg: "./digitize/phone/digi-ph-home.png",
        dImg: "./digitize/digi-desk-home-slider.png",
        enParas: [
          "In this section , the home page of the website , various categories and slider of products whit discount are designed ",
          "In each category , users can view related products",
        ],
        frParas: [
          "در این بخش ، صفحه اصلی ، دسته بندی های مختلف سایت و اسلایدری از محصولات تخفیف دار قرار دارد.",
          "کاربران میتوانند در هر دسته بندی محصولات مرتبط را مشاهده کنند.",
        ],
      },
      {
        enTitle: "Individual Product Page",
        frTitle: "صفحه جزعیات محصول",
        icon: "",
        pImg: "./digitize/phone/digi-ph-phones.png",
        dImg: "./digitize/digi-desk-singleSection-laptops.png",
        enParas: [
          "There is the individual page for each product ",
          "Users can view all the details of the selected product on this page",
          "They can chose the color and add the product in shopping cart",
        ],
        frParas: [
          "برای هر محصول صفحه فردی طراحی شده است",
          "کاربر میتواند جزعیات کامل محصولات را مشاهده کند ",
          "رنگ مورد نظر خود را انتخاب کرده و به سبد خرید اضافه کند",
        ],
      },
      {
        enTitle: "Shopping Cart",
        frTitle: "سبد خرید",
        icon: "",
        pImg: "./digitize/phone/digi-ph-cart.png",
        dImg: "./digitize/digi-desk-cart.png",
        enParas: [
          "Users can add products to their shopping cart",
          "They can see the details of added products",
          "They can increase or decrease the number of selected products",
          "ّFinally , They can see the total price and complete their purchase",
        ],
        frParas: [
          "کابر ها میتوانند محصولات را به سبد خرید اضافه کنند",
          "میتوانند جزعیات محصولات اضافه شده را مشاهده کنند",
          "همچنین میتوانند تعداد هر محصول را افزایش یا کاهش دهند",
          " و در نهایت میتوانند جمع قیمت نهایی را مشاهده و خرید خود را تکمیل کنند",
        ],
      },
      {
        enTitle: "Wishlist",
        frTitle: "علاقمندی ها",
        icon: "",
        pImg: "./digitize/phone/digi-ph-interests.png",
        dImg: "./digitize/digi-desk-singleSection-laptops.png",
        enParas: [
          "Users can add their favorite products to their wishlist",
          "They can see the details of the added products and add them to the cart. ",
        ],
        frParas: [
          "کاربران میتوانند محصولات مورد علاقه خود را به لیست علاقمندی اضافه کنند",
          "تمام جزعیات محصول قابل مشاهده میباشد و میتوانند ان را به سبد خرید خود اضافه کنند.",
        ],
      },
      {
        enTitle: "Product Filters",
        frTitle: "فیلتر محصولات",
        icon: "",
        pImg: "./digitize/phone/digi-ph-filters.png",
        dImg: "./digitize/digi-desk-phones.png",
        enParas: [
          "Users can filter products in each category based on their specification",
          "The filter options for different categories are depending on the product attributes within them!",
        ],
        frParas: [
          "کاربران میتوانند محصولات در هر دسته بندی را بر اساس ویژگی های آنها فیلتر کنند.",
          "!گزینه های فیلتر برای دسته بندی های مختلف بستگی به ویژگی های محصولات داخل آنها دارد",
        ],
      },
      {
        enTitle: "Product Search",
        frTitle: "جستجوی محصول",
        icon: "",
        pImg: "./digitize/phone/digi-ph-phones.png",
        dImg: "./digitize/digi-desk-singleSection-laptops.png",
        enParas: [
          "Users can search among all the products on the site based on the product name",
        ],
        frParas: [
          "کاربران میتوانند بر اساس نام محصول بین تمامی محصولات جستجو کنند.",
        ],
      },
    ],
  },
  {
    id: 1,
    enTitle: "DigiTize",
    frTitle: "دیجی تایز",
    tools: [
      { title: "React Js", icon: <FaReact /> },
      { title: "Tailwind Css", icon: <SiTailwindcss /> },
      { title: "Swiper" },
      { title: "Formik React", icon: <FaReact /> },
      { title: "NextUi", icon: <SiNextui /> },
      { title: "Axios", icon: <SiAxios /> },
      { title: "React Context" },
      { title: "React Reducer" },
    ],
    mainImages: {
      pImg: "./digitize/phone/digi-ph-home.png",
      dImg: "./digitize/digi-desk-home.png",
    },
    order: 2,
    description: [
      {
        enTitle: "Home Page and Categories",
        frTitle: "صفحه اصلی و دسته بندی ها",
        icon: "",
        pImg: "./digitize/phone/digi-ph-home.png",
        dImg: "./digitize/digi-desk-home-slider.png",
        enParas: [
          "In this section , the home page of the website , various categories and slider of products whit discount are designed ",
          "In each category , users can view related products",
        ],
        frParas: [
          "در این بخش ، صفحه اصلی ، دسته بندی های مختلف سایت و اسلایدری از محصولات تخفیف دار قرار دارد.",
          "کاربران میتوانند در هر دسته بندی محصولات مرتبط را مشاهده کنند.",
        ],
      },
      {
        enTitle: "Individual Product Page",
        frTitle: "صفحه جزعیات محصول",
        icon: "",
        pImg: "./digitize/phone/digi-ph-phones.png",
        dImg: "./digitize/digi-desk-singleSection-laptops.png",
        enParas: [
          "There is the individual page for each product ",
          "Users can view all the details of the selected product on this page",
          "They can chose the color and add the product in shopping cart",
        ],
        frParas: [
          "برای هر محصول صفحه فردی طراحی شده است",
          "کاربر میتواند جزعیات کامل محصولات را مشاهده کند ",
          "رنگ مورد نظر خود را انتخاب کرده و به سبد خرید اضافه کند",
        ],
      },
      {
        enTitle: "Shopping Cart",
        frTitle: "سبد خرید",
        icon: "",
        pImg: "./digitize/phone/digi-ph-cart.png",
        dImg: "./digitize/digi-desk-cart.png",
        enParas: [
          "Users can add products to their shopping cart",
          "They can see the details of added products",
          "They can increase or decrease the number of selected products",
          "ّFinally , They can see the total price and complete their purchase",
        ],
        frParas: [
          "کابر ها میتوانند محصولات را به سبد خرید اضافه کنند",
          "میتوانند جزعیات محصولات اضافه شده را مشاهده کنند",
          "همچنین میتوانند تعداد هر محصول را افزایش یا کاهش دهند",
          " و در نهایت میتوانند جمع قیمت نهایی را مشاهده و خرید خود را تکمیل کنند",
        ],
      },
      {
        enTitle: "Wishlist",
        frTitle: "علاقمندی ها",
        icon: "",
        pImg: "./digitize/phone/digi-ph-interests.png",
        dImg: "./digitize/digi-desk-singleSection-laptops.png",
        enParas: [
          "Users can add their favorite products to their wishlist",
          "They can see the details of the added products and add them to the cart. ",
        ],
        frParas: [
          "کاربران میتوانند محصولات مورد علاقه خود را به لیست علاقمندی اضافه کنند",
          "تمام جزعیات محصول قابل مشاهده میباشد و میتوانند ان را به سبد خرید خود اضافه کنند.",
        ],
      },
      {
        enTitle: "Product Filters",
        frTitle: "فیلتر محصولات",
        icon: "",
        pImg: "./digitize/phone/digi-ph-filters.png",
        dImg: "./digitize/digi-desk-phones.png",
        enParas: [
          "Users can filter products in each category based on their specification",
          "The filter options for different categories are depending on the product attributes within them!",
        ],
        frParas: [
          "کاربران میتوانند محصولات در هر دسته بندی را بر اساس ویژگی های آنها فیلتر کنند.",
          "!گزینه های فیلتر برای دسته بندی های مختلف بستگی به ویژگی های محصولات داخل آنها دارد",
        ],
      },
      {
        enTitle: "Product Search",
        frTitle: "جستجوی محصول",
        icon: "",
        pImg: "./digitize/phone/digi-ph-phones.png",
        dImg: "./digitize/digi-desk-singleSection-laptops.png",
        enParas: [
          "Users can search among all the products on the site based on the product name",
        ],
        frParas: [
          "کاربران میتوانند بر اساس نام محصول بین تمامی محصولات جستجو کنند.",
        ],
      },
    ],
  },
  {
    id: 1,
    enTitle: "DigiTize",
    frTitle: "دیجی تایز",
    tools: [
      { title: "React Js", icon: <FaReact /> },
      { title: "Tailwind Css", icon: <SiTailwindcss /> },
      { title: "Swiper" },
      { title: "Formik React", icon: <FaReact /> },
      { title: "NextUi", icon: <SiNextui /> },
      { title: "Axios", icon: <SiAxios /> },
      { title: "React Context" },
      { title: "React Reducer" },
    ],
    mainImages: {
      pImg: "./digitize/phone/digi-ph-home.png",
      dImg: "./digitize/digi-desk-home.png",
    },
    order: 2,
    description: [
      {
        enTitle: "Home Page and Categories",
        frTitle: "صفحه اصلی و دسته بندی ها",
        icon: "",
        pImg: "./digitize/phone/digi-ph-home.png",
        dImg: "./digitize/digi-desk-home-slider.png",
        enParas: [
          "In this section , the home page of the website , various categories and slider of products whit discount are designed ",
          "In each category , users can view related products",
        ],
        frParas: [
          "در این بخش ، صفحه اصلی ، دسته بندی های مختلف سایت و اسلایدری از محصولات تخفیف دار قرار دارد.",
          "کاربران میتوانند در هر دسته بندی محصولات مرتبط را مشاهده کنند.",
        ],
      },
      {
        enTitle: "Individual Product Page",
        frTitle: "صفحه جزعیات محصول",
        icon: "",
        pImg: "./digitize/phone/digi-ph-phones.png",
        dImg: "./digitize/digi-desk-singleSection-laptops.png",
        enParas: [
          "There is the individual page for each product ",
          "Users can view all the details of the selected product on this page",
          "They can chose the color and add the product in shopping cart",
        ],
        frParas: [
          "برای هر محصول صفحه فردی طراحی شده است",
          "کاربر میتواند جزعیات کامل محصولات را مشاهده کند ",
          "رنگ مورد نظر خود را انتخاب کرده و به سبد خرید اضافه کند",
        ],
      },
      {
        enTitle: "Shopping Cart",
        frTitle: "سبد خرید",
        icon: "",
        pImg: "./digitize/phone/digi-ph-cart.png",
        dImg: "./digitize/digi-desk-cart.png",
        enParas: [
          "Users can add products to their shopping cart",
          "They can see the details of added products",
          "They can increase or decrease the number of selected products",
          "ّFinally , They can see the total price and complete their purchase",
        ],
        frParas: [
          "کابر ها میتوانند محصولات را به سبد خرید اضافه کنند",
          "میتوانند جزعیات محصولات اضافه شده را مشاهده کنند",
          "همچنین میتوانند تعداد هر محصول را افزایش یا کاهش دهند",
          " و در نهایت میتوانند جمع قیمت نهایی را مشاهده و خرید خود را تکمیل کنند",
        ],
      },
      {
        enTitle: "Wishlist",
        frTitle: "علاقمندی ها",
        icon: "",
        pImg: "./digitize/phone/digi-ph-interests.png",
        dImg: "./digitize/digi-desk-singleSection-laptops.png",
        enParas: [
          "Users can add their favorite products to their wishlist",
          "They can see the details of the added products and add them to the cart. ",
        ],
        frParas: [
          "کاربران میتوانند محصولات مورد علاقه خود را به لیست علاقمندی اضافه کنند",
          "تمام جزعیات محصول قابل مشاهده میباشد و میتوانند ان را به سبد خرید خود اضافه کنند.",
        ],
      },
      {
        enTitle: "Product Filters",
        frTitle: "فیلتر محصولات",
        icon: "",
        pImg: "./digitize/phone/digi-ph-filters.png",
        dImg: "./digitize/digi-desk-phones.png",
        enParas: [
          "Users can filter products in each category based on their specification",
          "The filter options for different categories are depending on the product attributes within them!",
        ],
        frParas: [
          "کاربران میتوانند محصولات در هر دسته بندی را بر اساس ویژگی های آنها فیلتر کنند.",
          "!گزینه های فیلتر برای دسته بندی های مختلف بستگی به ویژگی های محصولات داخل آنها دارد",
        ],
      },
      {
        enTitle: "Product Search",
        frTitle: "جستجوی محصول",
        icon: "",
        pImg: "./digitize/phone/digi-ph-phones.png",
        dImg: "./digitize/digi-desk-singleSection-laptops.png",
        enParas: [
          "Users can search among all the products on the site based on the product name",
        ],
        frParas: [
          "کاربران میتوانند بر اساس نام محصول بین تمامی محصولات جستجو کنند.",
        ],
      },
    ],
  },
  //   {
  //     id: 2,
  //     title: "Booking Hotel App",
  //     tools: [
  //       "React Js",
  //       "Tailwind Css",
  //       "Leaflet Js",
  //       "React UseForm",
  //       "Axios",
  //       "React DateRange",
  //       { tool: "React Js", icon: {} },
  //     ],
  //     img: "./booking-hotel.png",
  //     order: 1,
  //     desktopSlides: [
  //       "./digitize/Annotation 2023-11-19 182634.png",
  //       "./digitize/Annotation 2023-11-19 182725.png",
  //       "./digitize/Annotation 2023-11-19 182850.png",
  //       "./digitize/Annotation 2023-11-19 185904.png",
  //       "./digitize/Annotation 2023-11-19 190048.png",
  //       "./digitize/Annotation 2023-11-19 190150.png",
  //       "./digitize/Annotation 2023-11-19 190241.png",
  //     ],
  //     phoneSlides: [
  //       "./digitize/phone/Annotation 2023-11-19 190719.png",
  //       "./digitize/phone/Annotation 2023-11-19 190745.png",
  //       "./digitize/phone/Annotation 2023-11-19 190819.png",
  //       "./digitize/phone/Annotation 2023-11-19 190902.png",
  //       "./digitize/phone/Annotation 2023-11-19 190954.png",
  //       "./digitize/phone/Annotation 2023-11-19 191039.png",
  //       "./digitize/phone/Annotation 2023-11-19 191108.png",
  //       "./digitize/phone/Annotation 2023-11-19 191141.png",
  //     ],
  //   },
  //   {
  //     id: 3,
  //     title: "My Resume",
  //     tools: ["React Js", "Tailwind Css", "Particle Js"],
  //     img: "./portfolios.png",
  //     order: 2,
  //     desktopSlides: [
  //       "./digitize/Annotation 2023-11-19 182634.png",
  //       "./digitize/Annotation 2023-11-19 182725.png",
  //       "./digitize/Annotation 2023-11-19 182850.png",
  //       "./digitize/Annotation 2023-11-19 185904.png",
  //       "./digitize/Annotation 2023-11-19 190048.png",
  //       "./digitize/Annotation 2023-11-19 190150.png",
  //       "./digitize/Annotation 2023-11-19 190241.png",
  //     ],
  //     phoneSlides: [
  //       "./digitize/phone/Annotation 2023-11-19 190719.png",
  //       "./digitize/phone/Annotation 2023-11-19 190745.png",
  //       "./digitize/phone/Annotation 2023-11-19 190819.png",
  //       "./digitize/phone/Annotation 2023-11-19 190902.png",
  //       "./digitize/phone/Annotation 2023-11-19 190954.png",
  //       "./digitize/phone/Annotation 2023-11-19 191039.png",
  //       "./digitize/phone/Annotation 2023-11-19 191108.png",
  //       "./digitize/phone/Annotation 2023-11-19 191141.png",
  //     ],
  //   },
  //   {
  //     id: 4,
  //     title: "Inventory WebApplication",
  //     tools: ["JavaScript", "Tailwind Css", "OOP"],
  //     img: "./inventory.png",
  //     order: 2,
  //     desktopSlides: [
  //       "./digitize/Annotation 2023-11-19 182634.png",
  //       "./digitize/Annotation 2023-11-19 182725.png",
  //       "./digitize/Annotation 2023-11-19 182850.png",
  //       "./digitize/Annotation 2023-11-19 185904.png",
  //       "./digitize/Annotation 2023-11-19 190048.png",
  //       "./digitize/Annotation 2023-11-19 190150.png",
  //       "./digitize/Annotation 2023-11-19 190241.png",
  //     ],
  //     phoneSlides: [
  //       "./digitize/phone/Annotation 2023-11-19 190719.png",
  //       "./digitize/phone/Annotation 2023-11-19 190745.png",
  //       "./digitize/phone/Annotation 2023-11-19 190819.png",
  //       "./digitize/phone/Annotation 2023-11-19 190902.png",
  //       "./digitize/phone/Annotation 2023-11-19 190954.png",
  //       "./digitize/phone/Annotation 2023-11-19 191039.png",
  //       "./digitize/phone/Annotation 2023-11-19 191108.png",
  //       "./digitize/phone/Annotation 2023-11-19 191141.png",
  //     ],
  //   },
];
